#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Aug 19 23:23:47 CEST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=4
shaderPack=ComplementaryReimagined_r5.3.zip
