Overworld.armorChancePerSlotPercentace=55 #Armor Chance Per Slot Percentage [0-100] | default: 55
Overworld.maxArmorPieces=4 #Max Armor Pieces | default: 4
Overworld.minArmorPieces=0 #Min Armor Pieces | default: 0
Overworld.maxProtectionLevel=5 #Max Protection Level | default: 5
Overworld.minProtectionLevel=2 #Min Protection Level | default: 2
Overworld.leatherArmorWeight=5 #Leather Armor Weight | default: 5
Overworld.goldArmorWeight=5 #Gold Armor Weight | default: 5
Overworld.chainmailArmorWeight=10 #Chainmail Armor Weight | default: 10
Overworld.ironArmorWeight=10 #Iron Armor Weight | default: 10
Overworld.diamondArmorWeight=40 #Diamond Armor Weight | default: 40
Overworld.netheriteArmorWeight=30 #Netherite Armor Weight | default: 30
Overworld.Zombie.zombieSwordChance=50 #Zombie Sword Chance | default: 50
Overworld.Zombie.goldSwordWeight=20 #Gold Sword Weight | default: 20
Overworld.Zombie.ironSwordWeight=30 #Iron Sword Weight | default: 30
Overworld.Zombie.diamondSwordWeight=30 #Diamond Sword Weight | default: 30
Overworld.Zombie.netheriteSwordWeight=20 #Netherite Sword Weight | default: 20
Overworld.Zombie.maxSharpnessLevel=5 #Max Sharpness Level | default: 5
Overworld.Zombie.minSharpnessLevel=2 #Min Sharpness Level | default: 2
Overworld.Zombie.fireAspectChance=13 #Fire Aspect Chance [0-100] | default: 13
Overworld.Zombie.knockbackChance=13 #Knockback Chance [0-100] | default: 13
Overworld.Skeleton.maxPowerLevel=5 #Max Power Level | default: 5
Overworld.Skeleton.minPowerLevel=2 #Min Power Level | default: 2
Overworld.Skeleton.flameChance=13 #Flame Chance [0-100] | default: 13
Overworld.Skeleton.punchChance=13 #Punch Chance [0-100] | default: 13
Nether.armorChancePerSlotPercentace=80 #Armor Chance Per Slot [0-100] | default: 80
Nether.maxArmorPieces=4 #Max Armor Pieces | default: 4
Nether.minArmorPieces=0 #Min Armor Pieces | default: 0
Nether.maxProtectionLevel=5 #Max Protection Level | default: 5
Nether.minProtectionLevel=2 #Min Protection Level | default: 2
Nether.goldArmorWeight=65 #Gold Armor Weight | default: 65
Nether.netheriteArmorWeight=35 #Netherite Armor Weight | default: 35
Nether.goldSwordWeight=65 #Gold Sword Weight | default: 65
Nether.netheriteSwordWeight=35 #Netherite Sword Weight | default: 35
Nether.maxSharpnessLevel=5 #Max Sharpness Level | default: 5
Nether.minSharpnessLevel=2 #Min Sharpness Level | default: 2
Nether.fireAspectChance=13 #Fire Aspect Chance [0-100] | default: 13
Nether.knockbackChance=13 #Knockback Chance [0-100] | default: 13

